### ISSUE TITLE
please add BEIR

### ISSUE THREAD

**Issue by osoese** [BenTokenFinance/benswapbch-assets#52]
![0xc2FAa57d340e127b43DFa5F5886e54A2D192Ee64](https://user-images.githubusercontent.com/31746846/152697160-07aeaf3e-ee03-404d-82d6-01f7dd3670d6.png)

**Comment by BenTokenFinance** [comment]
contract address?

**Comment by osoese** [comment]
I had named the image the contract address, sorry about that.
Here it is: `0x686C2bb8B9aa391E340E1362A89daB55520504C9`
https://www.smartscan.cash/address/0x686C2bb8B9aa391E340E1362A89daB55520504C9
