### ISSUE TITLE
please add WEGEM

### ISSUE THREAD

**Issue by osoese** [BenTokenFinance/benswapbch-assets#59]
contract: 0xF6AD9a164a0f1CfE5C3e7bc5c2B9E684de4aC9c5
https://www.smartscan.cash/address/0xF6AD9a164a0f1CfE5C3e7bc5c2B9E684de4aC9c5
![EGEM_official-512x512](https://user-images.githubusercontent.com/31746846/154168427-14f80ec6-b46b-44df-a152-6f38662aab8a.png)

**Comment by BenTokenFinance** [comment]
added
