### ISSUE TITLE
Please add Rastjn

### ISSUE THREAD

**Issue by KonraToken** [BenTokenFinance/benswapbch-assets#69]
Please add Rastjn & it's logo as we are building liquidity and have multiple ranches on BenSwap for the project.  

Contract Address: 0xc2A19D0A31Eb5CF6720F99c06869e283BbEF10F3

![RastjnLogo150 (1)](https://user-images.githubusercontent.com/91860683/168911455-618c6720-a870-4c7f-9aaf-3cad761d6806.png)

 
Please let me know if you need the description, social accounts or anything else. 

Thank you.

**Comment by BenTokenFinance** [comment]
Hi, I added Logo. 
And yes if you need token listing in the default search list, please provide de descriptions etc for me to add it. Thanks

**Comment by KonraToken** [comment]
I just saw this today as I've been bogged down with my day job the last two weeks working way too many hours. Here is the full description and information for Rastjn so it can be fully listed on BenSwap. It was created with the SEP20 Factory and we use a lot of Ranches and other BenSwap tools to develop the token further to help showcase the awesome resources of SmartBCH so I hope we can collaborate more in the future to boost SmartBCH. Please let me know if you need more information about the other Kingdom tokens as well if they're not fully listed yet (Konra and Narath).

Name: Rastjn
Symbol: RASTJN
Contract Address: 0xc2A19D0A31Eb5CF6720F99c06869e283BbEF10F3
Type: SEP20 Token / Liquidity Generator

It was created with SEP20 Factory on BenSwap

Decimals: 18

Total Supply on Chain: 21,000,000
Burned: 10,533.787
Circulating Supply:  20,989,466.213


Transaction Fee:
10%

Yield:
7%

Liquidity:
1.5%

Charity/Marketing: 
1.5%

Market Cap: 630 K

Description: 

Rastjn is the third of the Konra Kingdom tokens, it's our sassy reflection token with a twist. It's farmable in multiple ranches or you can hold it in your wallet in a form of auto staking to receive passive reflections. This deflationary token will help us grow SmartBCH by collaborating with other projects and DEX's to bring DEFI to everyone while simultaneously showcasing the many awesome attributes of SmartBCH and Bitcoin Cash. 


Website: https://konratoken.com/rastjn/

Twitter: https://twitter.com/Konratoken

**Comment by BenTokenFinance** [comment]
Hi. Token added to the default list. (Konra and Narath are already listed before). Thanks for the great work of promoting SmartBCH and utilizing our multiple features!
